
default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: db/sunnystorm_development

test:
  <<: *default
  database: db/sunnystorm_test

production:
  <<: *default
  database: db/sunnystorm_production
